"use client";

import { useState } from "react";
import Tooltip from "@/components/Tooltip";
import { validateShareholders } from "@/lib/pump/fee-shares-validation";
import { PANDA_REWARDS_POOL } from "@/lib/pump/constants";
import { truncateAddress } from "@/lib/format";

type Recipient = { id: string; label: string; address: string; pct: string; locked?: boolean };

const REWARDS_POOL = PANDA_REWARDS_POOL?.toBase58() || null;

function makeDefaultRecipients(creator: string): Recipient[] {
  const rows: Recipient[] = [{ id: "creator", label: "Creator", address: creator, pct: REWARDS_POOL ? "80" : "100", locked: true }];
  if (REWARDS_POOL) {
    rows.push({ id: "holders", label: "Holders", address: REWARDS_POOL, pct: "20", locked: true });
  }
  return rows;
}

/**
 * A real, optional step in Create: decides who receives this coin's Pump.fun
 * creator fees, wired on-chain via `@pump-fun/pump-sdk`'s fee-sharing config
 * (see `src/lib/pump/fee-sharing.ts`) — not a PANDA-side setting. Skippable:
 * a creator can launch without it and keep 100% of fees the default way.
 */
export default function FeeDistributionStep({
  creator,
  onSkip,
  onContinue,
  submitting,
}: {
  creator: string;
  onSkip: () => void;
  onContinue: (shareholders: { address: string; shareBps: number }[]) => void;
  submitting?: boolean;
}) {
  const [enabled, setEnabled] = useState(false);
  const [recipients, setRecipients] = useState<Recipient[]>(() => makeDefaultRecipients(creator));

  const totalPct = recipients.reduce((sum, r) => sum + (parseFloat(r.pct) || 0), 0);

  function updateRecipient(id: string, patch: Partial<Recipient>) {
    setRecipients((rows) => rows.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  }

  function addRecipient() {
    if (recipients.length >= 10) return;
    setRecipients((rows) => [...rows, { id: crypto.randomUUID(), label: "Recipient", address: "", pct: "0" }]);
  }

  function removeRecipient(id: string) {
    setRecipients((rows) => rows.filter((r) => r.id !== id));
  }

  const shareholders = recipients.map((r) => ({ address: r.address.trim(), shareBps: Math.round((parseFloat(r.pct) || 0) * 100) }));
  const validationError = enabled ? validateShareholders(shareholders) : null;

  if (!enabled) {
    return (
      <div className="rounded-2xl border border-paper/15 bg-ink-raised p-5">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="font-medium">Fee Distribution</p>
            <p className="mt-1 text-sm text-panda-grey">
              By default you keep 100% of this coin&apos;s Pump.fun creator fees. You can instead split them, real and
              on-chain, between yourself and your holders.
            </p>
          </div>
        </div>
        <div className="mt-4 flex gap-2">
          <button
            type="button"
            onClick={() => setEnabled(true)}
            className="rounded-full border border-paper/20 px-4 py-2 text-sm font-semibold hover:border-paper/40 transition"
          >
            Set up fee distribution
          </button>
          <button
            type="button"
            onClick={onSkip}
            className="rounded-full px-4 py-2 text-sm font-medium text-panda-grey hover:text-paper transition-colors"
          >
            Skip — keep 100%
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-paper/15 bg-ink-raised p-5">
      <div className="flex items-center gap-1.5">
        <p className="font-medium">Fee Distribution</p>
        <Tooltip label="Sets a real on-chain Pump.fun fee-sharing config for this coin. Once submitted, this is a second transaction you sign after the coin itself is created.">
          <span className="cursor-help text-xs text-panda-grey/70">ⓘ</span>
        </Tooltip>
      </div>
      <p className="mt-1 text-sm text-panda-grey">Who receives the creator fees generated by this coin?</p>

      <div className="mt-4 space-y-2">
        {recipients.map((r) => (
          <div key={r.id} className="flex items-center gap-2 rounded-xl bg-ink px-3 py-2.5">
            <div className="min-w-0 flex-1">
              {r.locked ? (
                <>
                  <p className="text-sm font-medium">{r.label}</p>
                  <p className="truncate text-xs text-panda-grey">{truncateAddress(r.address)}</p>
                </>
              ) : (
                <input
                  value={r.address}
                  onChange={(e) => updateRecipient(r.id, { address: e.target.value.trim() })}
                  placeholder="Recipient wallet address"
                  className="w-full bg-transparent text-sm outline-none placeholder:text-panda-grey"
                />
              )}
            </div>
            <div className="flex shrink-0 items-center gap-1">
              <input
                value={r.pct}
                onChange={(e) => updateRecipient(r.id, { pct: e.target.value.replace(/[^0-9.]/g, "") })}
                inputMode="decimal"
                className="w-14 rounded-lg bg-paper/5 px-2 py-1.5 text-right text-sm outline-none"
              />
              <span className="text-xs text-panda-grey">%</span>
            </div>
            {!r.locked && (
              <button
                type="button"
                onClick={() => removeRecipient(r.id)}
                className="shrink-0 text-panda-grey hover:text-clay-red transition-colors"
                aria-label="Remove recipient"
              >
                ✕
              </button>
            )}
          </div>
        ))}
      </div>

      {recipients.length < 10 && (
        <button
          type="button"
          onClick={addRecipient}
          className="mt-3 text-sm font-medium text-paper/70 hover:text-paper transition-colors"
        >
          + Add recipient
        </button>
      )}

      <div className="mt-4 flex items-center justify-between border-t border-paper/10 pt-3 text-sm">
        <span className="text-panda-grey">Total allocation</span>
        <span className={`font-semibold ${totalPct === 100 ? "text-bamboo" : "text-clay-red"}`}>{totalPct.toFixed(2)}%</span>
      </div>
      {validationError && <p className="mt-2 text-xs text-clay-red">{validationError}</p>}
      {!REWARDS_POOL && (
        <p className="mt-2 text-xs text-panda-grey">
          Holder rewards routing isn&apos;t configured on PANDA yet — add a holders wallet manually, or route entirely
          to yourself/other recipients for now.
        </p>
      )}

      <div className="mt-4 flex gap-2">
        <button
          type="button"
          disabled={!!validationError || submitting}
          onClick={() => onContinue(shareholders)}
          className="rounded-full bg-paper px-4 py-2 text-sm font-semibold text-ink transition hover:brightness-90 disabled:cursor-not-allowed disabled:opacity-40"
        >
          {submitting ? "Confirm in wallet…" : "Save fee distribution"}
        </button>
        <button
          type="button"
          onClick={() => setEnabled(false)}
          disabled={submitting}
          className="rounded-full px-4 py-2 text-sm font-medium text-panda-grey hover:text-paper transition-colors disabled:opacity-40"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
