import { createNoopSigner, publicKey, signerIdentity } from "@metaplex-foundation/umi";
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { create, fetchAsset, mplCore, ruleSet } from "@metaplex-foundation/mpl-core";

/**
 * Minting NFTs as Metaplex Core assets, non-custodially: the server only BUILDS
 * the transaction; the creator's own wallet signs and pays. Nothing is ever
 * marked published until the asset is read back from the chain and matches
 * exactly what PANDA specified (`verifyAsset`).
 *
 * Every NFT is created with:
 *  - ImmutableMetadata  — name and URI can never be changed (once added, Core offers no way
 *                         to remove it, so its mere presence is the guarantee);
 *  - Royalties          — the theme's royalty to the creator, ruleSet "None"
 *                         (i.e. NOT enforced by the token itself: marketplaces
 *                         that respect it will pay it, and PANDA's own market
 *                         does — a royalty is not guaranteed elsewhere);
 *  - Attributes         — theme + content hash, written on-chain for provenance;
 *  - AddBlocker         — seals the asset: nobody (not even the creator, as update authority)
 *                         can add plugins or external adapters later. Without it a creator could
 *                         attach, say, a lifecycle hook after selling and make the NFT untransferable;
 *  and Royalties and Attributes have authority "None": nobody, including the
 *  creator and PANDA, can alter them afterwards.
 * The creator is the owner and the update authority.
 */

export type MintAttributes = { key: string; value: string }[];

export type ExpectedAsset = {
  assetAddress: string;
  /** Who must own the asset right now (the creator right after minting; the seller once it is on sale). */
  owner: string;
  /** The original creator: the update authority and the royalty recipient. Defaults to `owner` (the mint case). */
  creator?: string;
  name: string;
  uri: string;
  royaltyBps: number;
  attributes: MintAttributes;
};

export function expectedAttributes(theme: { title: string; themeId: number }, contentHash: string, branch?: { title: string; branchId: number }): MintAttributes {
  return [
    { key: "Theme", value: theme.title },
    { key: "Theme ID", value: String(theme.themeId) },
    { key: "Content Hash", value: contentHash },
    // Only NFTs of a branch carry these; NFTs minted before branches existed are unchanged.
    ...(branch ? [{ key: "Branch", value: branch.title }, { key: "Branch ID", value: String(branch.branchId) }] : []),
  ];
}

/** The attributes an NFT record must have on-chain — one place for the mint, the confirmation and the market. */
export function attributesOfRecord(rec: { themeTitle: string; themeId: number; sha256: string; branchId?: number; branchTitle?: string }): MintAttributes {
  return expectedAttributes({ title: rec.themeTitle, themeId: rec.themeId }, rec.sha256, rec.branchId !== undefined && rec.branchTitle ? { title: rec.branchTitle, branchId: rec.branchId } : undefined);
}

export type BuiltMint = { transactionBase64: string; blockhash: string; lastValidBlockHeight: number };

/**
 * Builds the unsigned transaction. The asset keypair is generated by the
 * client (only it can sign for that address); the wallet pays and owns.
 * `blockhash` can be injected (tests); otherwise it is fetched from the RPC.
 */
export async function buildMintTransaction(args: {
  rpcUrl: string;
  wallet: string;
  expected: ExpectedAsset;
  blockhash?: { blockhash: string; lastValidBlockHeight: number };
}): Promise<BuiltMint> {
  const { rpcUrl, wallet, expected } = args;
  const walletKey = publicKey(wallet);
  const assetSigner = createNoopSigner(publicKey(expected.assetAddress));

  const umi = createUmi(rpcUrl).use(mplCore()).use(signerIdentity(createNoopSigner(walletKey)));

  const builder = create(umi, {
    asset: assetSigner,
    name: expected.name,
    uri: expected.uri,
    owner: walletKey,
    updateAuthority: walletKey,
    plugins: [
      { type: "ImmutableMetadata" },
      { type: "AddBlocker" },
      {
        type: "Royalties",
        basisPoints: expected.royaltyBps,
        creators: [{ address: walletKey, percentage: 100 }],
        ruleSet: ruleSet("None"),
        authority: { type: "None" },
      },
      { type: "Attributes", attributeList: expected.attributes, authority: { type: "None" } },
    ],
  });

  const bh = args.blockhash ?? (await umi.rpc.getLatestBlockhash());
  const tx = await builder.setBlockhash(bh).setFeePayer(createNoopSigner(walletKey)).build(umi);
  return {
    transactionBase64: Buffer.from(umi.transactions.serialize(tx)).toString("base64"),
    blockhash: bh.blockhash,
    lastValidBlockHeight: Number(bh.lastValidBlockHeight),
  };
}

// ---- verification ----------------------------------------------------------

/** The subset of a deserialized Core asset this check reads (structurally compatible with mpl-core's AssetV1). */
export type AssetLike = {
  publicKey: string | { toString(): string };
  owner: string | { toString(): string };
  name: string;
  uri: string;
  updateAuthority: { type: string; address?: string | { toString(): string } };
  royalties?: {
    authority: { type: string };
    basisPoints: number;
    creators: { address: string | { toString(): string }; percentage: number }[];
    ruleSet: { type: string };
  };
  attributes?: { authority: { type: string }; attributeList: { key: string; value: string }[] };
  immutableMetadata?: { authority: { type: string } };
  addBlocker?: { authority: { type: string } };
  [other: string]: unknown;
};

/** Fields of a deserialized asset that are not plugins. Anything else that is present is treated as a plugin. */
const BASE_FIELDS = new Set(["publicKey", "header", "pluginHeader", "key", "owner", "updateAuthority", "name", "uri", "seq"]);
const ALLOWED_PLUGINS = new Set(["royalties", "attributes", "immutableMetadata", "addBlocker"]);

const str = (v: string | { toString(): string } | undefined) => (v === undefined ? "" : String(v));

/**
 * Compares an on-chain asset with what PANDA specified. Returns null when it
 * matches EXACTLY, otherwise the first mismatch. The plugin check is an
 * allow-list: a creator who edits the transaction before signing (say, adding a
 * PermanentTransferDelegate so they could later take the NFT back from a
 * buyer, or a lifecycle hook) makes the asset fail verification and it is
 * never published or listed.
 */
export type VerifyOptions = {
  /**
   * PANDA's marketplace authority. When set, a TransferDelegate plugin whose authority is exactly this
   * address is permitted (that is what an active listing looks like); any other transfer delegate is still refused.
   */
  marketAuthority?: string;
  /** Require the marketplace TransferDelegate to be present (a listing that can actually be sold). */
  requireMarketDelegate?: boolean;
};

export function verifyAsset(asset: AssetLike, expected: ExpectedAsset, opts: VerifyOptions = {}): string | null {
  const creator = expected.creator ?? expected.owner;
  if (str(asset.publicKey) !== expected.assetAddress) return "asset address differs";
  if (str(asset.owner) !== expected.owner) return "owner differs";
  if (asset.name !== expected.name) return "name differs";
  if (asset.uri !== expected.uri) return "uri differs";
  if (asset.updateAuthority.type !== "Address" || str(asset.updateAuthority.address) !== creator) return "update authority differs";

  for (const key of Object.keys(asset)) {
    if (BASE_FIELDS.has(key)) continue;
    const value = asset[key];
    if (value === undefined || value === null || (Array.isArray(value) && value.length === 0)) continue;
    if (key === "transferDelegate" && opts.marketAuthority) continue; // checked precisely below
    if (!ALLOWED_PLUGINS.has(key)) return `unexpected plugin: ${key}`;
  }

  const td = asset.transferDelegate as { authority?: { type?: string; address?: string | { toString(): string } } } | undefined | null;
  if (td) {
    if (!opts.marketAuthority || td.authority?.type !== "Address" || str(td.authority.address) !== opts.marketAuthority) return "unexpected transfer delegate";
  } else if (opts.requireMarketDelegate) {
    return "PANDA's marketplace is not approved to transfer this asset";
  }

  if (!asset.immutableMetadata) return "metadata is not immutable";
  if (!asset.addBlocker) return "asset isn't sealed against added plugins";

  const r = asset.royalties;
  if (!r) return "royalties plugin missing";
  if (r.authority.type !== "None") return "royalties can still be changed";
  if (r.basisPoints !== expected.royaltyBps) return "royalty differs";
  if (r.ruleSet.type !== "None") return "unexpected royalty rule set";
  if (r.creators.length !== 1 || str(r.creators[0].address) !== creator || r.creators[0].percentage !== 100) return "royalty creators differ";

  const a = asset.attributes;
  if (!a) return "attributes plugin missing";
  if (a.authority.type !== "None") return "attributes can still be changed";
  if (a.attributeList.length !== expected.attributes.length || a.attributeList.some((x, i) => x.key !== expected.attributes[i].key || x.value !== expected.attributes[i].value)) {
    return "attributes differ";
  }
  return null;
}

/** Reads the asset from the chain and verifies it. Returns null when it matches, else the reason (or "asset not found"). */
export async function verifyMintedAsset(rpcUrl: string, expected: ExpectedAsset, opts: VerifyOptions = {}): Promise<string | null> {
  const umi = createUmi(rpcUrl).use(mplCore());
  let asset;
  try {
    asset = await fetchAsset(umi, publicKey(expected.assetAddress), { commitment: "confirmed" });
  } catch {
    return "asset not found on-chain";
  }
  return verifyAsset(asset as unknown as AssetLike, expected, opts);
}
